#include "services/PersistentSave.h"
#include <cstddef>
#include <cstring>
#include <new>
#if defined(ARDUINO_ARCH_ESP32)
#include <Arduino.h>
#include <SPIFFS.h>
#include <esp_system.h>
#endif

static_assert(sizeof(GameSave) < 28000, "GameSave no longer fits the expanded redundant NVS layout");

namespace {
struct CurrentSaveHeader {
  uint32_t magic;
  uint16_t version;
  uint16_t payloadSize;
  uint32_t sequence;
  // GameSave contains uint64_t fields and is 8-byte aligned. Record therefore
  // has four zero padding bytes between sequence and payload on ESP32.
  uint32_t alignmentPadding;
};
static_assert(sizeof(CurrentSaveHeader) == 16, "Persistent save header layout changed");

// Never use `save = GameSave{}` on-device.  GameSave contains the complete
// 386-slot Box; the temporary value generated by that expression is larger
// than the default Arduino loop-task stack and causes a watchdog reset during
// a brand-new boot.  Initialize the caller-owned buffer in place instead.
void initializeNewSave(GameSave& save) {
  std::memset(&save, 0, sizeof(save));
  save.collection.nextUid = 1;
  // The unique Mega Stone is now earned from the post-Hoenn special boss.
  save.ownedMachines = 0;
  save.inventory.balls[static_cast<uint8_t>(PokeBallType::PokeBall)] = 10;
  save.inventory.balls[static_cast<uint8_t>(PokeBallType::GreatBall)] = 3;
  save.inventory.balls[static_cast<uint8_t>(PokeBallType::UltraBall)] = 1;
  save.inventory.medicine[static_cast<uint8_t>(BattleItem::Potion)] = 5;
  save.encounterCharges.available = EncounterCharges::kMaximum;
  save.encounterCharges.rechargeTargetSeconds = EncounterCharges::kMinimumRechargeSeconds;
  save.wildEncounterClock.targetSeconds = WildEncounterClock::kMinimumSeconds;
  save.wildEncounterClock.rngState = 0x91E10DA5U;
  save.wildEncounterClock.available = WildEncounterClock::kMaximum;
  save.battle.trainerProfileId = 0xFF;
  save.battle.gymId = 0xFF;
  save.battle.rngState = 0xA341316CU;
  save.battle.unlockedGeneration = 1;
  save.gymProgress.unlockedGeneration = 1;
  save.money = 3000;
  save.mart.elapsedSeconds = 86400;
  save.mart.rng = 0x4D415254U;
  save.egg.bonusWindowSeconds = 86400;
  save.settings.brightnessPercent = 80;
  save.settings.screenTimeoutIndex = 1;
  save.homePetPlacement.background = 0xFF;
}

// A new physical Pokegochi must not start on the same deterministic random
// stream as every other unit.  The eFuse MAC makes the stream device-specific
// while ESP32's hardware RNG and the boot timer ensure that even a deliberate
// factory reset does not replay the unit's previous game.  These values are
// written into the first redundant save record, so subsequent boots continue
// the persisted streams instead of reseeding an existing game.
void seedNewSaveRandomness(GameSave& save) {
#if defined(ARDUINO_ARCH_ESP32)
  const uint64_t mac = ESP.getEfuseMac();
  uint64_t entropy = mac ^ (static_cast<uint64_t>(esp_random()) << 32U) ^
                     static_cast<uint64_t>(esp_random()) ^
                     (static_cast<uint64_t>(micros()) << 17U);
  const auto nextSeed = [&entropy](uint64_t stream) {
    uint64_t value = (entropy += 0x9E3779B97F4A7C15ULL) ^ stream;
    value = (value ^ (value >> 30U)) * 0xBF58476D1CE4E5B9ULL;
    value = (value ^ (value >> 27U)) * 0x94D049BB133111EBULL;
    value ^= value >> 31U;
    uint32_t seed = static_cast<uint32_t>(value ^ (value >> 32U));
    return seed ? seed : static_cast<uint32_t>(stream | 1U);
  };
  save.wildEncounterClock.rngState = nextSeed(0x57494C44ULL);  // "WILD"
  save.battle.rngState = nextSeed(0x42415454ULL);              // "BATT"
  save.mart.rng = nextSeed(0x4D415254ULL);                    // "MART"
  Serial.printf("[IDENTITY] new-save MAC=%04llX%08llX RNG=%08lX/%08lX/%08lX\n",
                static_cast<unsigned long long>((mac >> 32U) & 0xFFFFU),
                static_cast<unsigned long long>(mac & 0xFFFFFFFFULL),
                static_cast<unsigned long>(save.wildEncounterClock.rngState),
                static_cast<unsigned long>(save.battle.rngState),
                static_cast<unsigned long>(save.mart.rng));
#endif
}

#if defined(ARDUINO_ARCH_ESP32)
const char* savePath(const char* key) {
  return std::strcmp(key, "save_a") == 0 ? "/pokegochi_save_a.bin" : "/pokegochi_save_b.bin";
}
const char* temporarySavePath(const char* key) {
  return std::strcmp(key, "save_a") == 0 ? "/pokegochi_save_a.tmp" : "/pokegochi_save_b.tmp";
}
#endif
}

bool PersistentSave::begin(void* migrationScratch, size_t migrationScratchBytes) {
  if (!preferences_.begin("pokegochi", false)) {
#if defined(ARDUINO_ARCH_ESP32)
    Serial.println("[SAVE] Preferences open failed");
#endif
    return false;
  }
#if defined(ARDUINO_ARCH_ESP32)
  // The two complete save records are much larger than a safe NVS blob.  The
  // internal SPIFFS partition is dedicated to them and remains available even
  // when the removable SD card is absent.
  if (!SPIFFS.begin(true)) {
    Serial.println("[SAVE] SPIFFS mount failed");
    return false;
  }
  // Current records are read and committed as streams, so no permanent
  // Record-sized heap allocation is needed. The renderer's still-unused boot
  // arena is borrowed only if an older save must be migrated.
  scratch_ = migrationScratchBytes >= sizeof(Record)
                 ? reinterpret_cast<Record*>(migrationScratch)
                 : nullptr;
  Serial.printf("[SAVE] storage ready migration-scratch=%s/%u record=%u heap=%u block=%u\n",
                scratch_ ? "OK" : "NONE", static_cast<unsigned>(migrationScratchBytes),
                static_cast<unsigned>(sizeof(Record)),
                static_cast<unsigned>(ESP.getFreeHeap()),
                static_cast<unsigned>(ESP.getMaxAllocHeap()));
#else
  (void)migrationScratch;
  (void)migrationScratchBytes;
  if (!scratch_) scratch_ = new (std::nothrow) Record;
  if (!scratch_) return false;
#endif
  return true;
}
uint32_t PersistentSave::crc32Update(uint32_t crc, const uint8_t* data, size_t length) const {
  for (size_t i = 0; i < length; ++i) {
    crc ^= data[i];
    for (uint8_t bit = 0; bit < 8; ++bit)
      crc = (crc >> 1U) ^ (0xEDB88320U & (0U - (crc & 1U)));
  }
  return crc;
}
uint32_t PersistentSave::crc32(const uint8_t* data, size_t length) const {
  return ~crc32Update(0xFFFFFFFFU, data, length);
}
#if defined(ARDUINO_ARCH_ESP32)
bool PersistentSave::inspectCurrentRecord(const char* key, uint32_t& sequence) const {
  static_assert(offsetof(Record, payload) == sizeof(CurrentSaveHeader),
                "Streamed header must match the legacy Record layout");
  static_assert(offsetof(Record, crc) == sizeof(CurrentSaveHeader) + sizeof(GameSave),
                "Streamed payload must match the legacy Record layout");
  File file = SPIFFS.open(savePath(key), "r");
  if (!file || file.size() != static_cast<size_t>(sizeof(Record))) {
    if (file) file.close();
    return false;
  }
  CurrentSaveHeader header{};
  if (file.readBytes(reinterpret_cast<char*>(&header), sizeof(header)) != sizeof(header) ||
      header.magic != kMagic || header.version != kFormatVersion ||
      header.payloadSize != sizeof(GameSave)) {
    file.close();
    return false;
  }
  uint32_t crc = crc32Update(0xFFFFFFFFU,
      reinterpret_cast<const uint8_t*>(&header), sizeof(header));
  uint8_t chunk[256];
  size_t remaining = sizeof(GameSave);
  while (remaining) {
    const size_t requested = remaining < sizeof(chunk) ? remaining : sizeof(chunk);
    if (file.readBytes(reinterpret_cast<char*>(chunk), requested) != requested) {
      file.close();
      return false;
    }
    crc = crc32Update(crc, chunk, requested);
    remaining -= requested;
  }
  uint32_t storedCrc = 0;
  uint32_t trailingPadding = 0;
  const bool complete = file.readBytes(reinterpret_cast<char*>(&storedCrc), sizeof(storedCrc)) == sizeof(storedCrc) &&
      file.readBytes(reinterpret_cast<char*>(&trailingPadding), sizeof(trailingPadding)) == sizeof(trailingPadding);
  file.close();
  if (!complete || storedCrc != ~crc) return false;
  sequence = header.sequence;
  return true;
}

bool PersistentSave::loadCurrentRecord(const char* key, GameSave& save, uint32_t& sequence) const {
  File file = SPIFFS.open(savePath(key), "r");
  if (!file || file.size() != static_cast<size_t>(sizeof(Record))) {
    if (file) file.close();
    return false;
  }
  CurrentSaveHeader header{};
  if (file.readBytes(reinterpret_cast<char*>(&header), sizeof(header)) != sizeof(header) ||
      header.magic != kMagic || header.version != kFormatVersion ||
      header.payloadSize != sizeof(GameSave) ||
      file.readBytes(reinterpret_cast<char*>(&save), sizeof(save)) != sizeof(save)) {
    file.close();
    return false;
  }
  uint32_t storedCrc = 0;
  uint32_t trailingPadding = 0;
  const bool complete = file.readBytes(reinterpret_cast<char*>(&storedCrc), sizeof(storedCrc)) == sizeof(storedCrc) &&
      file.readBytes(reinterpret_cast<char*>(&trailingPadding), sizeof(trailingPadding)) == sizeof(trailingPadding);
  file.close();
  uint32_t crc = crc32Update(0xFFFFFFFFU,
      reinterpret_cast<const uint8_t*>(&header), sizeof(header));
  crc = crc32Update(crc, reinterpret_cast<const uint8_t*>(&save), sizeof(save));
  if (!complete || storedCrc != ~crc) return false;
  sequence = header.sequence;
  return true;
}
#endif
bool PersistentSave::readRecord(const char* key, Record& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool matches = file.size() == static_cast<size_t>(sizeof(Record)) &&
                       file.readBytes(reinterpret_cast<char*>(&record), sizeof(Record)) == sizeof(Record);
  file.close();
  return matches;
#else
  return preferences_.getBytesLength(key) == sizeof(Record) && preferences_.getBytes(key, &record, sizeof(Record)) == sizeof(Record);
#endif
}
bool PersistentSave::readRecordV9(const char* key, RecordV9& record) {
  return preferences_.getBytesLength(key) == sizeof(RecordV9) &&
         preferences_.getBytes(key, &record, sizeof(RecordV9)) == sizeof(RecordV9) &&
         record.magic == kMagic && record.version == 9 && record.payloadSize == sizeof(GameSaveV9) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV9, crc));
}
bool PersistentSave::readRecordV10(const char* key, RecordV10& record) {
  return preferences_.getBytesLength(key)==sizeof(RecordV10)&&preferences_.getBytes(key,&record,sizeof(record))==sizeof(record)&&
    record.magic==kMagic&&record.version==10&&record.payloadSize==sizeof(GameSaveV10)&&
    record.crc==crc32(reinterpret_cast<const uint8_t*>(&record),offsetof(RecordV10,crc));
}
bool PersistentSave::readRecordV11(const char* key, RecordV11& record) {
  return preferences_.getBytesLength(key)==sizeof(RecordV11)&&preferences_.getBytes(key,&record,sizeof(record))==sizeof(record)&&
    record.magic==kMagic&&record.version==11&&record.payloadSize==sizeof(GameSaveV11)&&
    record.crc==crc32(reinterpret_cast<const uint8_t*>(&record),offsetof(RecordV11,crc));
}
bool PersistentSave::readRecordV21(const char* key, RecordV21& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV21)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV21) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 21 &&
         record.payloadSize == sizeof(GameSaveV21) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV21, crc));
}
bool PersistentSave::readRecordV22(const char* key, RecordV22& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV22)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV22) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 22 &&
         record.payloadSize == sizeof(GameSaveV22) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV22, crc));
}
bool PersistentSave::readRecordV23(const char* key, RecordV23& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV23)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV23) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 23 &&
         record.payloadSize == sizeof(GameSaveV23) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV23, crc));
}
bool PersistentSave::readRecordV24(const char* key, RecordV24& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV24)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV24) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 24 &&
         record.payloadSize == sizeof(GameSaveV24) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV24, crc));
}
bool PersistentSave::readRecordV25(const char* key, RecordV25& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV25)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV25) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 25 &&
         record.payloadSize == sizeof(GameSaveV25) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV25, crc));
}
bool PersistentSave::readRecordV26(const char* key, RecordV26& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV26)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV26) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 26 &&
         record.payloadSize == sizeof(GameSaveV26) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV26, crc));
}
bool PersistentSave::readRecordV27(const char* key, RecordV27& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV27)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV27) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 27 &&
         record.payloadSize == sizeof(GameSaveV27) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV27, crc));
}
bool PersistentSave::readRecordV28(const char* key, RecordV28& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV28)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV28) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 28 &&
         record.payloadSize == sizeof(GameSaveV28) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV28, crc));
}
bool PersistentSave::readRecordV29(const char* key, RecordV29& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV29)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV29) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 29 &&
         record.payloadSize == sizeof(GameSaveV29) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV29, crc));
}
bool PersistentSave::readRecordV30(const char* key, RecordV30& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV30)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV30) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 30 &&
         record.payloadSize == sizeof(GameSaveV30) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV30, crc));
}
bool PersistentSave::readRecordV31(const char* key, RecordV31& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV31)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV31) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 31 &&
         record.payloadSize == sizeof(GameSaveV31) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV31, crc));
}
bool PersistentSave::readRecordV32(const char* key, RecordV32& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV32)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV32) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  return read && record.magic == kMagic && record.version == 32 &&
         record.payloadSize == sizeof(GameSaveV32) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV32, crc));
}
bool PersistentSave::readRecordV33(const char* key, RecordV33& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) {
    Serial.printf("[SAVE] V33 %s missing path=%s expected=%u\n", key, savePath(key),
                  static_cast<unsigned>(sizeof(RecordV33)));
    return false;
  }
  const size_t actualSize = file.size();
  const bool read = actualSize == static_cast<size_t>(sizeof(RecordV33)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV33) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  const uint32_t calculatedCrc = read
      ? crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV33, crc))
      : 0;
#if defined(ARDUINO_ARCH_ESP32)
  Serial.printf("[SAVE] V33 %s size=%u/%u read=%u magic=%08lX version=%u payload=%u/%u "
                "sequence=%lu crc=%08lX/%08lX\n",
                key, static_cast<unsigned>(actualSize), static_cast<unsigned>(sizeof(RecordV33)),
                read ? 1U : 0U, static_cast<unsigned long>(record.magic), record.version,
                record.payloadSize, static_cast<unsigned>(sizeof(GameSaveV33)),
                static_cast<unsigned long>(record.sequence), static_cast<unsigned long>(record.crc),
                static_cast<unsigned long>(calculatedCrc));
#endif
  return read && record.magic == kMagic && record.version == 33 &&
         record.payloadSize == sizeof(GameSaveV33) && record.crc == calculatedCrc;
}
bool PersistentSave::readRecordV34(const char* key, RecordV34& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const size_t actualSize = file.size();
  const bool read = actualSize == static_cast<size_t>(sizeof(RecordV34)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV34) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  const uint32_t calculatedCrc = read
      ? crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV34, crc)) : 0;
  return read && record.magic == kMagic && record.version == 34 &&
         record.payloadSize == sizeof(GameSaveV34) && record.crc == calculatedCrc;
}
bool PersistentSave::readRecordV35(const char* key, RecordV35& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV35)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV35) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  const uint32_t calculatedCrc = read
      ? crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV35, crc)) : 0;
  return read && record.magic == kMagic && record.version == 35 &&
         record.payloadSize == sizeof(GameSaveV35) && record.crc == calculatedCrc;
}
bool PersistentSave::readRecordV36(const char* key, RecordV36& record) {
#if defined(ARDUINO_ARCH_ESP32)
  File file = SPIFFS.open(savePath(key), "r");
  if (!file) return false;
  const bool read = file.size() == static_cast<size_t>(sizeof(RecordV36)) &&
                    file.readBytes(reinterpret_cast<char*>(&record), sizeof(record)) == sizeof(record);
  file.close();
#else
  const bool read = preferences_.getBytesLength(key) == sizeof(RecordV36) &&
                    preferences_.getBytes(key, &record, sizeof(record)) == sizeof(record);
#endif
  const uint32_t calculatedCrc = read
      ? crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(RecordV36, crc)) : 0;
  return read && record.magic == kMagic && record.version == 36 &&
         record.payloadSize == sizeof(GameSaveV36) && record.crc == calculatedCrc;
}
bool PersistentSave::valid(const Record& record) const {
  return record.magic == kMagic && record.version == kFormatVersion && record.payloadSize == sizeof(GameSave) &&
         record.crc == crc32(reinterpret_cast<const uint8_t*>(&record), offsetof(Record, crc));
}
bool PersistentSave::isNewer(uint32_t a, uint32_t b) const { return static_cast<int32_t>(a - b) > 0; }
SaveLoadResult PersistentSave::loadOrCreate(GameSave& save) {
  // GameSave is intentionally large (the Box is persistent). Keeping two or
  // more Records as automatic variables overflows the ESP32 Arduino task
  // stack before setup() can finish. Reuse one heap buffer while selecting the
  // newest redundant record instead.
  Record* record = scratch_;
  bool found = false;
  uint32_t selectedSequence = 0;
#if defined(ARDUINO_ARCH_ESP32)
  const char* selectedKey = nullptr;
  for (const char* key : {"save_a", "save_b"}) {
    uint32_t candidateSequence = 0;
    if (!inspectCurrentRecord(key, candidateSequence)) continue;
    if (!found || isNewer(candidateSequence, selectedSequence)) {
      selectedKey = key;
      selectedSequence = candidateSequence;
      found = true;
    }
  }
  if (found) {
    uint32_t loadedSequence = 0;
    if (!loadCurrentRecord(selectedKey, save, loadedSequence) || loadedSequence != selectedSequence)
      return SaveLoadResult::StorageError;
  }
#else
  if (!record) return SaveLoadResult::StorageError;
  for (const char* key : {"save_a", "save_b"}) {
    std::memset(record, 0, sizeof(*record));
    if (!readRecord(key, *record) || !valid(*record)) continue;
    if (!found || isNewer(record->sequence, selectedSequence)) {
      save = record->payload;
      selectedSequence = record->sequence;
      found = true;
    }
  }
#endif
  const bool gameWasStarted = preferences_.getBool("started", false);
  auto migrateLegacyMart = [&](const auto& oldMart) {
    // Avoid materialising a 102-byte aggregate temporary on the ESP32. GCC's
    // Xtensa 14.2 gimplifier also ICEs on that assignment inside this generic
    // migration lambda.
    std::memset(&save.mart, 0, sizeof(save.mart));
    save.mart.rng = oldMart.rng;
    save.mart.day = oldMart.day;
    save.mart.elapsedSeconds = 86400;
    // offer[0].remaining stays zero so Home performs the normal rotation the
    // first time the migrated Mart is opened, without coupling save loading
    // to the Economy module.
  };
  auto migrateBattleV25 = [&](const BattleStateV25& old) {
    save.battle.active=old.active;save.battle.kind=old.kind;save.battle.outcome=old.outcome;
    save.battle.playerUid=old.playerUid;std::memcpy(save.battle.opponents,old.opponents,sizeof(old.opponents));
    save.battle.opponentCount=old.opponentCount;save.battle.opponentIndex=old.opponentIndex;
    save.battle.trainerProfileId=old.trainerProfileId;save.battle.gymId=old.gymId;
    save.battle.playerVolatile=old.playerVolatile;std::memcpy(save.battle.playerHeldItems,old.playerHeldItems,sizeof(old.playerHeldItems));
    std::memcpy(save.battle.opponentVolatiles,old.opponentVolatiles,sizeof(old.opponentVolatiles));
    save.battle.rngState=old.rngState;save.battle.turn=old.turn;save.battle.rewardMoney=old.rewardMoney;
    save.battle.opponentItemUses=old.opponentItemUses;save.battle.gymStage=old.gymStage;
    save.battle.leagueRegion=old.leagueRegion;save.battle.leagueStage=old.leagueStage;
    save.battle.unlockedGeneration=old.unlockedGeneration;save.battle.weather=BattleWeather::Clear;save.battle.weatherTurns=0;
  };
  auto migrateBattleV26 = [&](const BattleStateV26& old) {
    save.battle.active=old.active;save.battle.kind=old.kind;save.battle.outcome=old.outcome;
    save.battle.playerUid=old.playerUid;std::memcpy(save.battle.opponents,old.opponents,sizeof(old.opponents));
    save.battle.opponentCount=old.opponentCount;save.battle.opponentIndex=old.opponentIndex;
    save.battle.trainerProfileId=old.trainerProfileId;save.battle.gymId=old.gymId;
    save.battle.playerVolatile=old.playerVolatile;std::memcpy(save.battle.playerHeldItems,old.playerHeldItems,sizeof(old.playerHeldItems));
    std::memcpy(save.battle.opponentVolatiles,old.opponentVolatiles,sizeof(old.opponentVolatiles));
    save.battle.rngState=old.rngState;save.battle.turn=old.turn;save.battle.rewardMoney=old.rewardMoney;
    save.battle.opponentItemUses=old.opponentItemUses;save.battle.gymStage=old.gymStage;
    save.battle.leagueRegion=old.leagueRegion;save.battle.leagueStage=old.leagueStage;
    save.battle.unlockedGeneration=old.unlockedGeneration;save.battle.weather=old.weather;save.battle.weatherTurns=old.weatherTurns;
    save.battle.playerTransformed=old.playerTransformed;save.battle.playerOriginalSpeciesId=old.playerOriginalSpeciesId;
    save.battle.playerOriginalAbilityId=old.playerOriginalAbilityId;
    std::memcpy(save.battle.playerOriginalMoves,old.playerOriginalMoves,sizeof(old.playerOriginalMoves));
    std::memcpy(save.battle.playerOriginalMovePp,old.playerOriginalMovePp,sizeof(old.playerOriginalMovePp));
    save.battle.playerAbilityTraced=old.playerAbilityTraced;save.battle.playerPreTraceAbilityId=old.playerPreTraceAbilityId;
    save.battle.delayedToPlayer=DelayedAttackState{};save.battle.delayedToOpponent=DelayedAttackState{};
  };
  auto migrateBattleV27 = [&](const BattleStateV27& old) {
    save.battle.active=old.active;save.battle.kind=old.kind;save.battle.outcome=old.outcome;
    save.battle.playerUid=old.playerUid;std::memcpy(save.battle.opponents,old.opponents,sizeof(old.opponents));
    save.battle.opponentCount=old.opponentCount;save.battle.opponentIndex=old.opponentIndex;
    save.battle.trainerProfileId=old.trainerProfileId;save.battle.gymId=old.gymId;
    save.battle.playerVolatile=old.playerVolatile;std::memcpy(save.battle.playerHeldItems,old.playerHeldItems,sizeof(old.playerHeldItems));
    std::memcpy(save.battle.opponentVolatiles,old.opponentVolatiles,sizeof(old.opponentVolatiles));
    save.battle.rngState=old.rngState;save.battle.turn=old.turn;save.battle.rewardMoney=old.rewardMoney;
    save.battle.opponentItemUses=old.opponentItemUses;save.battle.gymStage=old.gymStage;
    save.battle.leagueRegion=old.leagueRegion;save.battle.leagueStage=old.leagueStage;
    save.battle.unlockedGeneration=old.unlockedGeneration;save.battle.weather=old.weather;save.battle.weatherTurns=old.weatherTurns;
    save.battle.playerTransformed=old.playerTransformed;save.battle.playerOriginalSpeciesId=old.playerOriginalSpeciesId;
    save.battle.playerOriginalAbilityId=old.playerOriginalAbilityId;
    std::memcpy(save.battle.playerOriginalMoves,old.playerOriginalMoves,sizeof(old.playerOriginalMoves));
    std::memcpy(save.battle.playerOriginalMovePp,old.playerOriginalMovePp,sizeof(old.playerOriginalMovePp));
    save.battle.playerAbilityTraced=old.playerAbilityTraced;save.battle.playerPreTraceAbilityId=old.playerPreTraceAbilityId;
    save.battle.delayedToPlayer=old.delayedToPlayer;save.battle.delayedToOpponent=old.delayedToOpponent;
    save.battle.playerSafeguardTurns=0;save.battle.opponentSafeguardTurns=0;
  };
  auto migrateBattleV28 = [&](const BattleStateV28& old) {
    save.battle.active=old.active;save.battle.kind=old.kind;save.battle.outcome=old.outcome;
    save.battle.playerUid=old.playerUid;std::memcpy(save.battle.opponents,old.opponents,sizeof(old.opponents));
    save.battle.opponentCount=old.opponentCount;save.battle.opponentIndex=old.opponentIndex;
    save.battle.trainerProfileId=old.trainerProfileId;save.battle.gymId=old.gymId;
    save.battle.playerVolatile=old.playerVolatile;std::memcpy(save.battle.playerHeldItems,old.playerHeldItems,sizeof(old.playerHeldItems));
    std::memcpy(save.battle.opponentVolatiles,old.opponentVolatiles,sizeof(old.opponentVolatiles));
    save.battle.rngState=old.rngState;save.battle.turn=old.turn;save.battle.rewardMoney=old.rewardMoney;
    save.battle.opponentItemUses=old.opponentItemUses;save.battle.gymStage=old.gymStage;
    save.battle.leagueRegion=old.leagueRegion;save.battle.leagueStage=old.leagueStage;
    save.battle.unlockedGeneration=old.unlockedGeneration;save.battle.weather=old.weather;save.battle.weatherTurns=old.weatherTurns;
    save.battle.playerTransformed=old.playerTransformed;save.battle.playerOriginalSpeciesId=old.playerOriginalSpeciesId;
    save.battle.playerOriginalAbilityId=old.playerOriginalAbilityId;
    std::memcpy(save.battle.playerOriginalMoves,old.playerOriginalMoves,sizeof(old.playerOriginalMoves));
    std::memcpy(save.battle.playerOriginalMovePp,old.playerOriginalMovePp,sizeof(old.playerOriginalMovePp));
    save.battle.playerAbilityTraced=old.playerAbilityTraced;save.battle.playerPreTraceAbilityId=old.playerPreTraceAbilityId;
    save.battle.delayedToPlayer=old.delayedToPlayer;save.battle.delayedToOpponent=old.delayedToOpponent;
    save.battle.playerSafeguardTurns=old.playerSafeguardTurns;
    save.battle.opponentSafeguardTurns=old.opponentSafeguardTurns;
    save.battle.playerReflectTurns=save.battle.opponentReflectTurns=0;
    save.battle.playerLightScreenTurns=save.battle.opponentLightScreenTurns=0;
    save.battle.playerMistTurns=save.battle.opponentMistTurns=0;
  };
  auto migrateVolatileV29 = [](CombatVolatile& current, const CombatVolatileV29& old) {
    current.attackStage=old.attackStage;current.defenseStage=old.defenseStage;
    current.spAttackStage=old.spAttackStage;current.spDefenseStage=old.spDefenseStage;
    current.speedStage=old.speedStage;current.accuracyStage=old.accuracyStage;
    current.evasionStage=old.evasionStage;current.confusionTurns=old.confusionTurns;
    current.trappedTurns=old.trappedTurns;current.criticalStage=old.criticalStage;
    current.flinched=old.flinched;current.protectedThisTurn=old.protectedThisTurn;
    current.recharging=old.recharging;current.substituteHp=old.substituteHp;
    current.disabledMove=old.disabledMove;current.encoreMove=old.encoreMove;
    current.chargingMove=old.chargingMove;current.lastMoveUsed=old.lastMoveUsed;
    current.choiceMove=old.choiceMove;current.heldItemOverride=old.heldItemOverride;
    current.hasHeldItemOverride=old.hasHeldItemOverride;
    current.heldItemSuppressed=old.heldItemSuppressed;current.seeded=old.seeded;
    current.toxicCounter=old.toxicCounter;current.sleepTurns=old.sleepTurns;
    current.stockpileCount=0;
  };
  auto migrateBattleV29 = [&](const BattleStateV29& old) {
    save.battle.active=old.active;save.battle.kind=old.kind;save.battle.outcome=old.outcome;
    save.battle.playerUid=old.playerUid;std::memcpy(save.battle.opponents,old.opponents,sizeof(old.opponents));
    save.battle.opponentCount=old.opponentCount;save.battle.opponentIndex=old.opponentIndex;
    save.battle.trainerProfileId=old.trainerProfileId;save.battle.gymId=old.gymId;
    migrateVolatileV29(save.battle.playerVolatile,old.playerVolatile);
    std::memcpy(save.battle.playerHeldItems,old.playerHeldItems,sizeof(old.playerHeldItems));
    for(uint8_t i=0;i<kOpponentTeamCapacity;++i)
      migrateVolatileV29(save.battle.opponentVolatiles[i],old.opponentVolatiles[i]);
    save.battle.rngState=old.rngState;save.battle.turn=old.turn;save.battle.rewardMoney=old.rewardMoney;
    save.battle.opponentItemUses=old.opponentItemUses;save.battle.gymStage=old.gymStage;
    save.battle.leagueRegion=old.leagueRegion;save.battle.leagueStage=old.leagueStage;
    save.battle.unlockedGeneration=old.unlockedGeneration;save.battle.weather=old.weather;
    save.battle.weatherTurns=old.weatherTurns;save.battle.playerTransformed=old.playerTransformed;
    save.battle.playerOriginalSpeciesId=old.playerOriginalSpeciesId;
    save.battle.playerOriginalAbilityId=old.playerOriginalAbilityId;
    std::memcpy(save.battle.playerOriginalMoves,old.playerOriginalMoves,sizeof(old.playerOriginalMoves));
    std::memcpy(save.battle.playerOriginalMovePp,old.playerOriginalMovePp,sizeof(old.playerOriginalMovePp));
    save.battle.playerAbilityTraced=old.playerAbilityTraced;
    save.battle.playerPreTraceAbilityId=old.playerPreTraceAbilityId;
    save.battle.delayedToPlayer=old.delayedToPlayer;save.battle.delayedToOpponent=old.delayedToOpponent;
    save.battle.playerSafeguardTurns=old.playerSafeguardTurns;save.battle.opponentSafeguardTurns=old.opponentSafeguardTurns;
    save.battle.playerReflectTurns=old.playerReflectTurns;save.battle.opponentReflectTurns=old.opponentReflectTurns;
    save.battle.playerLightScreenTurns=old.playerLightScreenTurns;save.battle.opponentLightScreenTurns=old.opponentLightScreenTurns;
    save.battle.playerMistTurns=old.playerMistTurns;save.battle.opponentMistTurns=old.opponentMistTurns;
    save.battle.playerProtectChain=old.playerProtectChain;save.battle.opponentProtectChain=old.opponentProtectChain;
    save.battle.playerEndureThisTurn=old.playerEndureThisTurn;save.battle.opponentEndureThisTurn=old.opponentEndureThisTurn;
    save.battle.playerNightmare=old.playerNightmare;
    std::memcpy(save.battle.opponentNightmares,old.opponentNightmares,sizeof(old.opponentNightmares));
  };
  auto migrateBattleV30 = [&](const BattleStateV30& old) {
    save.battle.active=old.active;save.battle.kind=old.kind;save.battle.outcome=old.outcome;
    save.battle.playerUid=old.playerUid;std::memcpy(save.battle.opponents,old.opponents,sizeof(old.opponents));
    save.battle.opponentCount=old.opponentCount;save.battle.opponentIndex=old.opponentIndex;
    save.battle.trainerProfileId=old.trainerProfileId;save.battle.gymId=old.gymId;
    save.battle.playerVolatile=old.playerVolatile;std::memcpy(save.battle.playerHeldItems,old.playerHeldItems,sizeof(old.playerHeldItems));
    std::memcpy(save.battle.opponentVolatiles,old.opponentVolatiles,sizeof(old.opponentVolatiles));
    save.battle.rngState=old.rngState;save.battle.turn=old.turn;save.battle.rewardMoney=old.rewardMoney;
    save.battle.opponentItemUses=old.opponentItemUses;save.battle.gymStage=old.gymStage;
    save.battle.leagueRegion=old.leagueRegion;save.battle.leagueStage=old.leagueStage;
    save.battle.unlockedGeneration=old.unlockedGeneration;save.battle.weather=old.weather;save.battle.weatherTurns=old.weatherTurns;
    save.battle.playerTransformed=old.playerTransformed;save.battle.playerOriginalSpeciesId=old.playerOriginalSpeciesId;
    save.battle.playerOriginalAbilityId=old.playerOriginalAbilityId;
    std::memcpy(save.battle.playerOriginalMoves,old.playerOriginalMoves,sizeof(old.playerOriginalMoves));
    std::memcpy(save.battle.playerOriginalMovePp,old.playerOriginalMovePp,sizeof(old.playerOriginalMovePp));
    save.battle.playerAbilityTraced=old.playerAbilityTraced;save.battle.playerPreTraceAbilityId=old.playerPreTraceAbilityId;
    save.battle.delayedToPlayer=old.delayedToPlayer;save.battle.delayedToOpponent=old.delayedToOpponent;
    save.battle.playerSafeguardTurns=old.playerSafeguardTurns;save.battle.opponentSafeguardTurns=old.opponentSafeguardTurns;
    save.battle.playerReflectTurns=old.playerReflectTurns;save.battle.opponentReflectTurns=old.opponentReflectTurns;
    save.battle.playerLightScreenTurns=old.playerLightScreenTurns;save.battle.opponentLightScreenTurns=old.opponentLightScreenTurns;
    save.battle.playerMistTurns=old.playerMistTurns;save.battle.opponentMistTurns=old.opponentMistTurns;
    save.battle.playerProtectChain=old.playerProtectChain;save.battle.opponentProtectChain=old.opponentProtectChain;
    save.battle.playerEndureThisTurn=old.playerEndureThisTurn;save.battle.opponentEndureThisTurn=old.opponentEndureThisTurn;
    save.battle.playerNightmare=old.playerNightmare;
    std::memcpy(save.battle.opponentNightmares,old.opponentNightmares,sizeof(old.opponentNightmares));
    // New V31 multi-turn state starts clear. A V30 save could not have a
    // functioning Bide timer, and its Encore marker had no valid duration.
    save.battle.playerBide=BideState{};
    std::memset(save.battle.opponentBides,0,sizeof(save.battle.opponentBides));
    save.battle.playerVolatile.encoreMove=MoveId::None;
    for(uint8_t i=0;i<kOpponentTeamCapacity;++i)save.battle.opponentVolatiles[i].encoreMove=MoveId::None;
    save.battle.playerEncoreTurns=0;
    std::memset(save.battle.opponentEncoreTurns,0,sizeof(save.battle.opponentEncoreTurns));
  };
  if (!found) {
    // V37 enlarges the Mart from fifteen to twenty offers. Preserve every
    // permanent V36 field, then expire only the old shop rotation so its next
    // opening creates four complete pages using the new probabilities.
    static_assert(sizeof(Record)>=sizeof(RecordV36),"V37 record must hold the V36 migration buffer");
    RecordV36* legacy36=reinterpret_cast<RecordV36*>(record);
    bool legacy36Found=false;uint32_t legacy36Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy36,0,sizeof(*legacy36));
      if(!readRecordV36(key,*legacy36)||(legacy36Found&&!isNewer(legacy36->sequence,legacy36Sequence)))continue;
      initializeNewSave(save);const GameSaveV36& old=legacy36->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;
      save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;
      save.encounterCharges=old.encounterCharges;save.wildEncounterClock=old.wildEncounterClock;
      save.battle=old.battle;save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;
      save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;
      save.ownedMachines=old.ownedMachines;save.statistics=old.statistics;
      save.martSeenDay=old.martSeenDay;save.ppItems=old.ppItems;
      save.homePetPlacement=old.homePetPlacement;
      legacy36Sequence=legacy36->sequence;legacy36Found=true;
    }
    if(legacy36Found){sequence_=legacy36Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // Older formats still need one complete migration record. On hardware it
    // is the renderer arena borrowed before any visual scene exists.
    if (!record) return gameWasStarted ? SaveLoadResult::Corrupted : SaveLoadResult::StorageError;
    // V36 adds only the compact Home placement state. Preserve the complete
    // V35 game verbatim field-by-field and let the new placement start empty.
    static_assert(sizeof(Record)>=sizeof(RecordV35),"V36 record must hold the V35 migration buffer");
    RecordV35* legacy35=reinterpret_cast<RecordV35*>(record);
    bool legacy35Found=false;uint32_t legacy35Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy35,0,sizeof(*legacy35));
      if(!readRecordV35(key,*legacy35)||(legacy35Found&&!isNewer(legacy35->sequence,legacy35Sequence)))continue;
      initializeNewSave(save);const GameSaveV35& old=legacy35->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;
      save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;
      save.encounterCharges=old.encounterCharges;save.wildEncounterClock=old.wildEncounterClock;
      save.battle=old.battle;save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;
      save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;
      save.ownedMachines=old.ownedMachines;save.statistics=old.statistics;
      save.martSeenDay=old.martSeenDay;save.ppItems=old.ppItems;
      legacy35Sequence=legacy35->sequence;legacy35Found=true;
    }
    if(legacy35Found){sequence_=legacy35Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V35 expands the daily Mart from ten to fifteen products. Preserve every
    // permanent field from V34 and deliberately expire only its old rotation;
    // the next Mart opening creates a complete, grouped 15-offer stock.
    static_assert(sizeof(Record)>=sizeof(RecordV34),"V35 record must hold the V34 migration buffer");
    RecordV34* legacy34=reinterpret_cast<RecordV34*>(record);
    bool legacy34Found=false;uint32_t legacy34Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy34,0,sizeof(*legacy34));
      if(!readRecordV34(key,*legacy34)||(legacy34Found&&!isNewer(legacy34->sequence,legacy34Sequence)))continue;
      initializeNewSave(save);const GameSaveV34& old=legacy34->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;
      save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;
      save.encounterCharges=old.encounterCharges;save.wildEncounterClock=old.wildEncounterClock;
      std::memcpy(&save.battle,old.battle.bytes,sizeof(old.battle.bytes));
      save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;save.money=old.money;
      migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;
      save.ownedMachines=old.ownedMachines;save.statistics=old.statistics;
      save.martSeenDay=old.martSeenDay;save.ppItems=old.ppItems;
      legacy34Sequence=legacy34->sequence;legacy34Found=true;
    }
    if(legacy34Found){sequence_=legacy34Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V34 appends exact Transform battle snapshots. V33 is otherwise an
    // exact prefix, so every collection/progression field survives intact.
    // An already transformed V33 battle cannot reconstruct the target's
    // frozen calculated stats; safely end only that temporary transformation
    // while preserving the battle itself.
    static_assert(sizeof(Record)>=sizeof(RecordV33),"V34 record must hold the V33 migration buffer");
    RecordV33* legacy33=reinterpret_cast<RecordV33*>(record);
    bool legacy33Found=false;uint32_t legacy33Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy33,0,sizeof(*legacy33));
      if(!readRecordV33(key,*legacy33)||(legacy33Found&&!isNewer(legacy33->sequence,legacy33Sequence)))continue;
      initializeNewSave(save);const GameSaveV33& old=legacy33->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;
      std::memcpy(&save.battle,old.battle.bytes,sizeof(old.battle.bytes));
      save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);
      save.moveLearning=old.moveLearning;save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;
      save.settings=old.settings;save.ownedMachines=old.ownedMachines;save.statistics=old.statistics;
      save.martSeenDay=old.martSeenDay;save.ppItems=old.ppItems;
      if(save.battle.playerTransformed){
        if(OwnedPokemon* player=CollectionLogic::find(save.collection,save.battle.playerUid)){
          player->speciesId=save.battle.playerOriginalSpeciesId;player->form=0;
          player->abilityId=save.battle.playerOriginalAbilityId;
          std::memcpy(player->moves,save.battle.playerOriginalMoves,sizeof(player->moves));
          std::memcpy(player->movePp,save.battle.playerOriginalMovePp,sizeof(player->movePp));
        }
        save.battle.playerTransformed=false;save.battle.playerMoveEffects.transformed=false;
      }
      if(save.battle.opponentIndex<kOpponentTeamCapacity&&
         save.battle.opponentMoveEffects[save.battle.opponentIndex].transformed){
        OwnedPokemon& opponent=save.battle.opponents[save.battle.opponentIndex];
        opponent.speciesId=132;opponent.form=0;CollectionLogic::refreshAbility(opponent);
        opponent.moves[0]=static_cast<MoveId>(144);opponent.movePp[0]=10;
        for(uint8_t slot=1;slot<kMoveSlots;++slot){opponent.moves[slot]=MoveId::None;opponent.movePp[slot]=0;}
        save.battle.opponentMoveEffects[save.battle.opponentIndex].transformed=false;
      }
      legacy33Sequence=legacy33->sequence;legacy33Found=true;
    }
    if(legacy33Found){sequence_=legacy33Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V33 appends PP-item stacks and repurposes each Pokemon's reserved care
    // bits for per-move PP Up counts. Existing V32 saves start with empty PP
    // item stacks and zero PP Ups; every other field remains intact.
    static_assert(sizeof(Record)>=sizeof(RecordV32),"V33 record must hold the V32 migration buffer");
    RecordV32* legacy32=reinterpret_cast<RecordV32*>(record);
    bool legacy32Found=false;uint32_t legacy32Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy32,0,sizeof(*legacy32));
      if(!readRecordV32(key,*legacy32)||(legacy32Found&&!isNewer(legacy32->sequence,legacy32Sequence)))continue;
      initializeNewSave(save);const GameSaveV32& old=legacy32->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;
      std::memcpy(&save.battle,old.battle.bytes,sizeof(old.battle.bytes));
      save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;
      save.ownedMachines=old.ownedMachines;save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;
      for(auto& pokemon:save.collection.box) pokemon.legacyCareCounterReserved=0;
      legacy32Sequence=legacy32->sequence;legacy32Found=true;
    }
    if(legacy32Found){sequence_=legacy32Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V32 appends the explicit state used by the formerly incomplete move
    // handlers. V31 is a byte-for-byte prefix, so preserve its complete
    // battle and clear only the newly introduced state.
    static_assert(sizeof(Record)>=sizeof(RecordV31),"V32 record must hold the V31 migration buffer");
    RecordV31* legacy31=reinterpret_cast<RecordV31*>(record);
    bool legacy31Found=false;uint32_t legacy31Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy31,0,sizeof(*legacy31));
      if(!readRecordV31(key,*legacy31)||(legacy31Found&&!isNewer(legacy31->sequence,legacy31Sequence)))continue;
      initializeNewSave(save);const GameSaveV31& old=legacy31->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;
      std::memcpy(&save.battle,old.battle.bytes,sizeof(old.battle.bytes));
      save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);
      save.moveLearning=old.moveLearning;save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;
      save.settings=old.settings;save.ownedMachines=old.ownedMachines;save.statistics=old.statistics;
      save.martSeenDay=old.martSeenDay;legacy31Sequence=legacy31->sequence;legacy31Found=true;
    }
    if(legacy31Found){sequence_=legacy31Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V30 gains persistent Bide/Encore timers in V31. Preserve every older
    // field and clear only the state that did not previously exist.
    static_assert(sizeof(GameSaveV30)==25648, "V30 save migration layout changed");
    static_assert(sizeof(Record)>=sizeof(RecordV30), "V31 record must hold the V30 migration buffer");
    RecordV30* legacy30=reinterpret_cast<RecordV30*>(record);
    bool legacy30Found=false;uint32_t legacy30Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy30,0,sizeof(*legacy30));
      if(!readRecordV30(key,*legacy30)||(legacy30Found&&!isNewer(legacy30->sequence,legacy30Sequence)))continue;
      initializeNewSave(save);const GameSaveV30& old=legacy30->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;migrateBattleV30(old.battle);save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;save.ownedMachines=old.ownedMachines;
      save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;legacy30Sequence=legacy30->sequence;legacy30Found=true;
    }
    if(legacy30Found){sequence_=legacy30Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // Early V29 used a smaller CombatVolatile but was shipped with the same
    // version number. Migrate it explicitly before trying older schemas.
    static_assert(sizeof(CombatVolatileV29)==32, "Early V29 volatile layout changed");
    static_assert(sizeof(GameSaveV29)==25640, "Early V29 save layout changed");
    static_assert(sizeof(Record)>=sizeof(RecordV29), "V30 record must hold the V29 migration buffer");
    RecordV29* legacy29=reinterpret_cast<RecordV29*>(record);
    bool legacy29Found=false;uint32_t legacy29Sequence=0;
    for(const char* key:{"save_a","save_b"}){
      std::memset(legacy29,0,sizeof(*legacy29));
      if(!readRecordV29(key,*legacy29)||(legacy29Found&&!isNewer(legacy29->sequence,legacy29Sequence)))continue;
      initializeNewSave(save);const GameSaveV29& old=legacy29->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;migrateBattleV29(old.battle);save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;save.ownedMachines=old.ownedMachines;
      save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;legacy29Sequence=legacy29->sequence;legacy29Found=true;
    }
    if(legacy29Found){sequence_=legacy29Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V29 adds the remaining persistent side conditions while preserving the
    // complete V28 save and any battle currently in progress.
    static_assert(sizeof(Record) >= sizeof(RecordV28), "V29 record must hold the V28 migration buffer");
    RecordV28* legacy28 = reinterpret_cast<RecordV28*>(record);
    bool legacy28Found = false; uint32_t legacy28Sequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy28, 0, sizeof(*legacy28));
      if (!readRecordV28(key, *legacy28) ||
          (legacy28Found && !isNewer(legacy28->sequence, legacy28Sequence))) continue;
      initializeNewSave(save);const GameSaveV28& old=legacy28->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;migrateBattleV28(old.battle);save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;save.ownedMachines=old.ownedMachines;
      save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;legacy28Sequence=legacy28->sequence;legacy28Found=true;
    }
    if(legacy28Found){sequence_=legacy28Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V28 adds side-wide Safeguard state while preserving the complete V27
    // game and any battle currently in progress.
    static_assert(sizeof(Record) >= sizeof(RecordV27), "V28 record must hold the V27 migration buffer");
    RecordV27* legacy27 = reinterpret_cast<RecordV27*>(record);
    bool legacy27Found = false; uint32_t legacy27Sequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy27, 0, sizeof(*legacy27));
      if (!readRecordV27(key, *legacy27) ||
          (legacy27Found && !isNewer(legacy27->sequence, legacy27Sequence))) continue;
      initializeNewSave(save);const GameSaveV27& old=legacy27->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;migrateBattleV27(old.battle);save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;save.ownedMachines=old.ownedMachines;
      save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;legacy27Sequence=legacy27->sequence;legacy27Found=true;
    }
    if(legacy27Found){sequence_=legacy27Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V27 persists delayed Future Sight/Doom Desire state while preserving
    // the complete V26 game and any battle currently in progress.
    static_assert(sizeof(Record) >= sizeof(RecordV26), "V27 record must hold the V26 migration buffer");
    RecordV26* legacy26 = reinterpret_cast<RecordV26*>(record);
    bool legacy26Found = false; uint32_t legacy26Sequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy26, 0, sizeof(*legacy26));
      if (!readRecordV26(key, *legacy26) ||
          (legacy26Found && !isNewer(legacy26->sequence, legacy26Sequence))) continue;
      initializeNewSave(save);const GameSaveV26& old=legacy26->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;migrateBattleV26(old.battle);save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;save.ownedMachines=old.ownedMachines;
      save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;legacy26Sequence=legacy26->sequence;legacy26Found=true;
    }
    if(legacy26Found){sequence_=legacy26Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V26 adds battle weather while preserving the complete V25 game.
    static_assert(sizeof(Record) >= sizeof(RecordV25), "V26 record must hold the V25 migration buffer");
    RecordV25* legacy25 = reinterpret_cast<RecordV25*>(record);
    bool legacy25Found = false; uint32_t legacy25Sequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy25, 0, sizeof(*legacy25));
      if (!readRecordV25(key, *legacy25) ||
          (legacy25Found && !isNewer(legacy25->sequence, legacy25Sequence))) continue;
      initializeNewSave(save);const GameSaveV25& old=legacy25->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;save.activePetSlot=old.activePetSlot;
      save.collection=old.collection;save.inventory=old.inventory;save.encounterCharges=old.encounterCharges;
      save.wildEncounterClock=old.wildEncounterClock;migrateBattleV25(old.battle);save.pokedex=old.pokedex;
      save.gymProgress=old.gymProgress;save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;save.ownedMachines=old.ownedMachines;
      save.statistics=old.statistics;save.martSeenDay=old.martSeenDay;legacy25Sequence=legacy25->sequence;legacy25Found=true;
    }
    if(legacy25Found){sequence_=legacy25Sequence;nextSlotA_=true;if(!commit(save))return SaveLoadResult::StorageError;return SaveLoadResult::Loaded;}

    // V25 added the persistent player statistics ledger.
    static_assert(sizeof(Record) >= sizeof(RecordV24), "V25 record must hold the V24 migration buffer");
    RecordV24* legacy24 = reinterpret_cast<RecordV24*>(record);
    bool legacy24Found = false; uint32_t legacy24Sequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy24, 0, sizeof(*legacy24));
      if (!readRecordV24(key, *legacy24) ||
          (legacy24Found && !isNewer(legacy24->sequence, legacy24Sequence))) continue;
      initializeNewSave(save);
      const GameSaveV24& old = legacy24->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;
      save.activePetSlot=old.activePetSlot;save.collection=old.collection;save.inventory=old.inventory;
      save.encounterCharges=old.encounterCharges;save.wildEncounterClock=old.wildEncounterClock;
      migrateBattleV25(old.battle);save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;
      save.money=old.money;migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;
      save.evolutionQueue=old.evolutionQueue;save.egg=old.egg;save.settings=old.settings;
      save.ownedMachines=old.ownedMachines;save.statistics=PlayerStatistics{};
      save.martSeenDay=old.mart.day;
      legacy24Sequence=legacy24->sequence;legacy24Found=true;
    }
    if (legacy24Found) {
      sequence_=legacy24Sequence;nextSlotA_=true;
      if (!commit(save)) return SaveLoadResult::StorageError;
      return SaveLoadResult::Loaded;
    }

    // V24 expands the daily Mart and adds the 58-bit unique TM/HM ownership
    // ledger. Preserve the complete V23 game, then rotate a fresh ten-slot
    // shop because the old record physically contained only seven offers.
    static_assert(sizeof(Record) >= sizeof(RecordV23), "V24 record must hold the V23 migration buffer");
    RecordV23* legacy23 = reinterpret_cast<RecordV23*>(record);
    bool legacy23Found = false; uint32_t legacy23Sequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy23, 0, sizeof(*legacy23));
      if (!readRecordV23(key, *legacy23) ||
          (legacy23Found && !isNewer(legacy23->sequence, legacy23Sequence))) continue;
      initializeNewSave(save);
      const GameSaveV23& old = legacy23->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;
      save.activePetSlot=old.activePetSlot;save.collection=old.collection;save.inventory=old.inventory;
      save.encounterCharges=old.encounterCharges;save.wildEncounterClock=old.wildEncounterClock;
      migrateBattleV25(old.battle);save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;
      save.money=old.money;save.moveLearning=old.moveLearning;save.evolutionQueue=old.evolutionQueue;
      save.egg=old.egg;save.settings=old.settings;save.ownedMachines=0;
      save.mart.rng=old.mart.rng;save.mart.day=old.mart.day;save.mart.elapsedSeconds=86400;
      legacy23Sequence=legacy23->sequence;legacy23Found=true;
    }
    if (legacy23Found) {
      sequence_=legacy23Sequence;nextSlotA_=true;
      if (!commit(save)) return SaveLoadResult::StorageError;
      return SaveLoadResult::Loaded;
    }

    // V23 adds battle-local counters used by the faithful Gen-III turn
    // resolver. Preserve the complete V22 game and initialise only those
    // newly introduced volatile fields.
    static_assert(sizeof(Record) >= sizeof(RecordV22), "V23 record must hold the V22 migration buffer");
    RecordV22* legacy22 = reinterpret_cast<RecordV22*>(record);
    bool legacy22Found = false;
    uint32_t legacy22Sequence = 0;
    auto copyVolatileV22 = [](CombatVolatile& destination, const CombatVolatileV22& source) {
      destination = CombatVolatile{};
      destination.attackStage=source.attackStage;destination.defenseStage=source.defenseStage;
      destination.spAttackStage=source.spAttackStage;destination.spDefenseStage=source.spDefenseStage;
      destination.speedStage=source.speedStage;destination.accuracyStage=source.accuracyStage;
      destination.evasionStage=source.evasionStage;destination.confusionTurns=source.confusionTurns;
      destination.trappedTurns=source.trappedTurns;destination.criticalStage=source.criticalStage;
      destination.flinched=source.flinched;destination.protectedThisTurn=source.protectedThisTurn;
      destination.recharging=source.recharging;destination.substituteHp=source.substituteHp;
      destination.disabledMove=source.disabledMove;destination.encoreMove=source.encoreMove;
      destination.chargingMove=source.chargingMove;destination.choiceMove=source.choiceMove;
      destination.heldItemOverride=source.heldItemOverride;
      destination.hasHeldItemOverride=source.hasHeldItemOverride;
      destination.heldItemSuppressed=source.heldItemSuppressed;
    };
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy22, 0, sizeof(*legacy22));
      if (!readRecordV22(key, *legacy22) ||
          (legacy22Found && !isNewer(legacy22->sequence, legacy22Sequence))) continue;
      initializeNewSave(save);
      const GameSaveV22& old = legacy22->payload;
      save.playTimeSeconds=old.playTimeSeconds;save.bootCount=old.bootCount;save.flags=old.flags;
      save.activePetSlot=old.activePetSlot;save.collection=old.collection;save.inventory=old.inventory;
      save.encounterCharges=old.encounterCharges;save.wildEncounterClock=old.wildEncounterClock;
      save.pokedex=old.pokedex;save.gymProgress=old.gymProgress;save.money=old.money;
      migrateLegacyMart(old.mart);save.moveLearning=old.moveLearning;save.evolutionQueue=old.evolutionQueue;
      save.egg=old.egg;save.settings=old.settings;
      BattleState& upgraded=save.battle;const BattleStateV22& previous=old.battle;
      upgraded.active=previous.active;upgraded.kind=previous.kind;upgraded.outcome=previous.outcome;
      upgraded.playerUid=previous.playerUid;std::memcpy(upgraded.opponents,previous.opponents,sizeof(upgraded.opponents));
      upgraded.opponentCount=previous.opponentCount;upgraded.opponentIndex=previous.opponentIndex;
      upgraded.trainerProfileId=previous.trainerProfileId;upgraded.gymId=previous.gymId;
      copyVolatileV22(upgraded.playerVolatile,previous.playerVolatile);
      std::memcpy(upgraded.playerHeldItems,previous.playerHeldItems,sizeof(upgraded.playerHeldItems));
      for(uint8_t i=0;i<kOpponentTeamCapacity;++i)copyVolatileV22(upgraded.opponentVolatiles[i],previous.opponentVolatiles[i]);
      upgraded.rngState=previous.rngState;upgraded.turn=previous.turn;upgraded.rewardMoney=previous.rewardMoney;
      upgraded.opponentItemUses=previous.opponentItemUses;upgraded.gymStage=previous.gymStage;
      upgraded.leagueRegion=previous.leagueRegion;upgraded.leagueStage=previous.leagueStage;
      upgraded.unlockedGeneration=previous.unlockedGeneration;
      legacy22Sequence=legacy22->sequence;legacy22Found=true;
    }
    if (legacy22Found) {
      sequence_=legacy22Sequence;nextSlotA_=true;
      if (!commit(save)) return SaveLoadResult::StorageError;
      return SaveLoadResult::Loaded;
    }

    // Upgrade the immediately preceding record in place.  It is safe to
    // reuse the already-reserved current Record buffer because V22 is larger
    // than V21; this avoids a second ~28 KiB heap allocation during boot.
    static_assert(sizeof(Record) >= sizeof(RecordV21), "V22 record must hold the V21 migration buffer");
    RecordV21* legacy21 = reinterpret_cast<RecordV21*>(record);
    bool legacy21Found = false;
    uint32_t legacy21Sequence = 0;
    auto copyPokemonV21 = [](OwnedPokemon& destination, const OwnedPokemonV21& source) {
      std::memset(&destination, 0, sizeof(destination));
      std::memcpy(&destination, &source, sizeof(source));
      // V21's trailing padding shares the location used by the first EVs in
      // the new struct, so explicitly zero the introduced training data.
      destination.evs = EffortValues{};
    };
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy21, 0, sizeof(*legacy21));
      if (!readRecordV21(key, *legacy21) ||
          (legacy21Found && !isNewer(legacy21->sequence, legacy21Sequence))) continue;
      initializeNewSave(save);
      const GameSaveV21& old = legacy21->payload;
      save.playTimeSeconds = old.playTimeSeconds;
      save.bootCount = old.bootCount;
      save.flags = old.flags;
      save.activePetSlot = old.activePetSlot;
      for (uint16_t index = 0; index < kBoxCapacity; ++index)
        copyPokemonV21(save.collection.box[index], old.collection.box[index]);
      std::memcpy(save.collection.party, old.collection.party, sizeof(save.collection.party));
      save.collection.nextUid = old.collection.nextUid;
      save.inventory = old.inventory;
      save.encounterCharges = old.encounterCharges;
      save.wildEncounterClock = old.wildEncounterClock;
      save.pokedex = old.pokedex;
      save.gymProgress = old.gymProgress;
      save.money = old.money;
      migrateLegacyMart(old.mart);
      save.moveLearning = old.moveLearning;
      save.evolutionQueue = old.evolutionQueue;
      save.egg = old.egg;
      save.settings = old.settings;

      const BattleStateV21& oldBattle = old.battle;
      BattleState& upgradedBattle = save.battle;
      upgradedBattle.active = oldBattle.active;
      upgradedBattle.kind = oldBattle.kind;
      upgradedBattle.outcome = oldBattle.outcome;
      upgradedBattle.playerUid = oldBattle.playerUid;
      for (uint8_t index = 0; index < kOpponentTeamCapacity; ++index)
        copyPokemonV21(upgradedBattle.opponents[index], oldBattle.opponents[index]);
      upgradedBattle.opponentCount = oldBattle.opponentCount;
      upgradedBattle.opponentIndex = oldBattle.opponentIndex;
      upgradedBattle.trainerProfileId = oldBattle.trainerProfileId;
      upgradedBattle.gymId = oldBattle.gymId;
      copyVolatileV22(upgradedBattle.playerVolatile, oldBattle.playerVolatile);
      std::memcpy(upgradedBattle.playerHeldItems, oldBattle.playerHeldItems,
                  sizeof(upgradedBattle.playerHeldItems));
      for (uint8_t index = 0; index < kOpponentTeamCapacity; ++index)
        copyVolatileV22(upgradedBattle.opponentVolatiles[index], oldBattle.opponentVolatiles[index]);
      upgradedBattle.rngState = oldBattle.rngState;
      upgradedBattle.turn = oldBattle.turn;
      upgradedBattle.rewardMoney = oldBattle.rewardMoney;
      upgradedBattle.opponentItemUses = oldBattle.opponentItemUses;
      upgradedBattle.gymStage = oldBattle.gymStage;
      upgradedBattle.leagueRegion = oldBattle.leagueRegion;
      upgradedBattle.leagueStage = oldBattle.leagueStage;
      upgradedBattle.unlockedGeneration = oldBattle.unlockedGeneration;
      legacy21Sequence = legacy21->sequence;
      legacy21Found = true;
    }
    if (legacy21Found) {
      sequence_ = legacy21Sequence;
      nextSlotA_ = true;
      if (!commit(save)) return SaveLoadResult::StorageError;
      return SaveLoadResult::Loaded;
    }

#if defined(ARDUINO_ARCH_ESP32)
    // Firmware built before the SPIFFS migration could fit only one complete
    // record in NVS. Preserve that first hardware save once, then release the
    // oversized NVS blobs so normal redundant file saves can take over.
    Record* nvsRecord = record;
    bool nvsFound = false;
    uint32_t nvsSequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(nvsRecord, 0, sizeof(*nvsRecord));
      const bool read = preferences_.getBytesLength(key) == sizeof(Record) &&
                        preferences_.getBytes(key, nvsRecord, sizeof(*nvsRecord)) == sizeof(*nvsRecord);
      if (!read || !valid(*nvsRecord) || (nvsFound && !isNewer(nvsRecord->sequence, nvsSequence))) continue;
      save = nvsRecord->payload;
      nvsSequence = nvsRecord->sequence;
      nvsFound = true;
    }
    if (nvsFound) {
      sequence_ = nvsSequence;
      nextSlotA_ = true;
      if (!commit(save)) return SaveLoadResult::StorageError;
      preferences_.remove("save_a");
      preferences_.remove("save_b");
      return SaveLoadResult::Loaded;
    }
#endif

    // Migrate the original shipped layout without another large heap
    // allocation. On a factory-erased ESP32 only about 14 KiB remains here,
    // while the renderer has already lent us a 64 KiB migration arena.
    // Reusing it also keeps the desktop persistence test on the same path.
    static_assert(sizeof(Record) >= sizeof(RecordV9),
                  "Current migration arena must hold the V9 record");
    RecordV9* legacy = reinterpret_cast<RecordV9*>(record);
    bool legacyFound = false;
    uint32_t legacySequence = 0;
    for (const char* key : {"save_a", "save_b"}) {
      std::memset(legacy, 0, sizeof(*legacy));
      if (!readRecordV9(key, *legacy)) continue;
      if (legacyFound && !isNewer(legacy->sequence, legacySequence)) continue;

      // Clear all fields introduced after V9 before copying the compatible
      // part of the battle state.
      initializeNewSave(save);
      save.playTimeSeconds = legacy->payload.playTimeSeconds;
      save.bootCount = legacy->payload.bootCount;
      save.flags = legacy->payload.flags;
      save.activePetSlot = legacy->payload.activePetSlot;
      save.collection = legacy->payload.collection;
      save.inventory = legacy->payload.inventory;
      save.encounterCharges = legacy->payload.encounterCharges;
      save.wildEncounterClock = legacy->payload.wildEncounterClock;
      save.battle.active = legacy->payload.battle.active;
      save.battle.kind = legacy->payload.battle.kind;
      save.battle.outcome = legacy->payload.battle.outcome;
      save.battle.playerUid = legacy->payload.battle.playerUid;
      std::memcpy(save.battle.opponents, legacy->payload.battle.opponents, sizeof(save.battle.opponents));
      save.battle.opponentCount = legacy->payload.battle.opponentCount;
      save.battle.opponentIndex = legacy->payload.battle.opponentIndex;
      save.battle.trainerProfileId = legacy->payload.battle.trainerProfileId;
      save.battle.gymId = legacy->payload.battle.gymId;
      save.battle.playerVolatile = legacy->payload.battle.playerVolatile;
      std::memcpy(save.battle.opponentVolatiles, legacy->payload.battle.opponentVolatiles,
                  sizeof(save.battle.opponentVolatiles));
      save.battle.rngState = legacy->payload.battle.rngState;
      save.battle.turn = legacy->payload.battle.turn;
      save.battle.rewardMoney = legacy->payload.battle.rewardMoney;
      save.pokedex = legacy->payload.pokedex;
      save.gymProgress = legacy->payload.gymProgress;
      save.money = legacy->payload.money;
      migrateLegacyMart(legacy->payload.mart);
      legacySequence = legacy->sequence;
      legacyFound = true;
    }
    if (legacyFound) {
      sequence_ = legacySequence;
      nextSlotA_ = true;
      if (!commit(save)) return SaveLoadResult::StorageError;
      return SaveLoadResult::Loaded;
    }

    if (gameWasStarted) return SaveLoadResult::Corrupted;
    initializeNewSave(save);
    seedNewSaveRandomness(save);
    if (!commit(save)) {
#if defined(ARDUINO_ARCH_ESP32)
      Serial.println("[SAVE] first-start commit failed");
#endif
      return SaveLoadResult::StorageError;
    }
    if (preferences_.putBool("started", true) != 1) {
#if defined(ARDUINO_ARCH_ESP32)
      Serial.println("[SAVE] first-start marker failed");
#endif
      return SaveLoadResult::StorageError;
    }
    return SaveLoadResult::FirstStart;
  }
  sequence_ = selectedSequence;
  // Alternate the next record after the most recently observed sequence.
  nextSlotA_ = (selectedSequence & 1U) == 0U;
  if (!gameWasStarted && preferences_.putBool("started", true) != 1) return SaveLoadResult::StorageError;
  return SaveLoadResult::Loaded;
}
bool PersistentSave::commit(const GameSave& save) {
  const uint32_t nextSequence = sequence_ + 1U;
  const char* key = nextSlotA_ ? "save_a" : "save_b";
#if defined(ARDUINO_ARCH_ESP32)
  // Write header, caller-owned payload and CRC as separate segments. Keeping a
  // second complete GameSave/Record in RAM is unnecessary and previously made
  // Preferences/SPIFFS fail whenever the 64 KiB graphics arena was reserved.
  static_assert(sizeof(Record) == sizeof(CurrentSaveHeader) + sizeof(GameSave) + 2U * sizeof(uint32_t),
                "Streamed current record must preserve the on-flash layout");
  const CurrentSaveHeader header{kMagic, kFormatVersion,
                                 static_cast<uint16_t>(sizeof(GameSave)), nextSequence, 0};
  uint32_t crcState = crc32Update(0xFFFFFFFFU,
      reinterpret_cast<const uint8_t*>(&header), sizeof(header));
  crcState = crc32Update(crcState, reinterpret_cast<const uint8_t*>(&save), sizeof(save));
  const uint32_t recordCrc = ~crcState;
  const uint32_t trailingPadding = 0;
  const char* finalPath = savePath(key);
  const char* temporaryPath = temporarySavePath(key);
  SPIFFS.remove(temporaryPath);
  File file = SPIFFS.open(temporaryPath, "w");
  const bool written = file &&
      file.write(reinterpret_cast<const uint8_t*>(&header), sizeof(header)) == sizeof(header) &&
      file.write(reinterpret_cast<const uint8_t*>(&save), sizeof(save)) == sizeof(save) &&
      file.write(reinterpret_cast<const uint8_t*>(&recordCrc), sizeof(recordCrc)) == sizeof(recordCrc) &&
      file.write(reinterpret_cast<const uint8_t*>(&trailingPadding), sizeof(trailingPadding)) == sizeof(trailingPadding);
  if (file) { file.flush(); file.close(); }
  if (!written || (SPIFFS.exists(finalPath) && !SPIFFS.remove(finalPath)) ||
      !SPIFFS.rename(temporaryPath, finalPath)) {
#if defined(ARDUINO_ARCH_ESP32)
    Serial.printf("[SAVE] write failed key=%s written=%u tmp=%u final=%u total=%u used=%u\n",
                  key, written ? 1U : 0U, SPIFFS.exists(temporaryPath) ? 1U : 0U,
                  SPIFFS.exists(finalPath) ? 1U : 0U,
                  static_cast<unsigned>(SPIFFS.totalBytes()),
                  static_cast<unsigned>(SPIFFS.usedBytes()));
#endif
    SPIFFS.remove(temporaryPath);
    return false;
  }
  uint32_t verifiedSequence = 0;
  const bool verified = inspectCurrentRecord(key, verifiedSequence) && verifiedSequence == nextSequence;
#else
  Record* record = scratch_;
  if (!record) return false;
  std::memset(record, 0, sizeof(*record));
  record->magic = kMagic; record->version = kFormatVersion;
  record->payloadSize = sizeof(GameSave); record->sequence = nextSequence; record->payload = save;
  record->crc = crc32(reinterpret_cast<const uint8_t*>(record), offsetof(Record, crc));
  if (preferences_.putBytes(key, record, sizeof(*record)) != sizeof(*record)) return false;
  std::memset(record, 0, sizeof(*record));
  const bool verified = readRecord(key, *record) && valid(*record);
#endif
  if (!verified) {
#if defined(ARDUINO_ARCH_ESP32)
    Serial.printf("[SAVE] verification failed key=%s expected=%lu observed=%lu size=%u\n",
                  key, static_cast<unsigned long>(nextSequence),
                  static_cast<unsigned long>(verifiedSequence),
                  static_cast<unsigned>(SPIFFS.open(finalPath, "r").size()));
#endif
    return false;
  }
  sequence_ = nextSequence;
  nextSlotA_ = !nextSlotA_;
  return true;
}

#if defined(POKEGOCHI_DEV_ALLOW_FACTORY_RESET)
bool PersistentSave::factoryResetForDevelopment() {
  sequence_ = 0;
  nextSlotA_ = true;
  return preferences_.clear();
}
#endif
