"""Generate compact Generation-I gameplay tables from the local pokefirered decomp."""

from __future__ import annotations

import re
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECOMP = ROOT / ".downloads" / "pokefirered-tree" / "pokefirered-master"
OUT = ROOT / "src" / "game" / "PokemonDataGenerated.inc"

constants = (DECOMP / "include/constants/species.h").read_text(encoding="utf-8")
species_source = (DECOMP / "src/data/pokemon/species_info.h").read_text(encoding="utf-8")
ability_constants = (DECOMP / "include/constants/abilities.h").read_text(encoding="utf-8")
evolution_source = (DECOMP / "src/data/pokemon/evolution.h").read_text(encoding="utf-8")

species = []
for symbol, number in re.findall(r"#define SPECIES_([A-Z0-9_]+)\s+(\d+)", constants):
    number = int(number)
    if 1 <= number <= 151:
        species.append((number, symbol))
species.sort()
symbol_to_id = {symbol: number for number, symbol in species}

type_map = {
    "NORMAL": "Normal", "FIGHTING": "Fighting", "FLYING": "Flying",
    "POISON": "Poison", "GROUND": "Ground", "ROCK": "Rock", "BUG": "Bug",
    "GHOST": "Ghost", "STEEL": "Steel", "MYSTERY": "Normal", "FIRE": "Fire",
    "WATER": "Water", "GRASS": "Grass", "ELECTRIC": "Electric",
    "PSYCHIC": "Psychic", "ICE": "Ice", "DRAGON": "Dragon", "DARK": "Dark",
}
growth_map = {
    "MEDIUM_FAST": "MediumFast", "ERRATIC": "Erratic", "FLUCTUATING": "Fluctuating",
    "MEDIUM_SLOW": "MediumSlow", "FAST": "Fast", "SLOW": "Slow",
}
display_names = {
    "NIDORAN_F": "NIDORAN F", "NIDORAN_M": "NIDORAN M", "MR_MIME": "MR. MIME",
    "FARFETCHD": "FARFETCH'D",
}

def field(block: str, name: str) -> str:
    match = re.search(rf"\.{name}\s*=\s*([A-Z0-9_]+)", block)
    if not match:
        raise ValueError(f"Missing {name}")
    return match.group(1)

rows = []
for number, symbol in species:
    match = re.search(rf"\[SPECIES_{symbol}\]\s*=\s*\{{(.*?)\n\s*\}},", species_source, re.S)
    if not match:
        raise ValueError(f"Missing species block {symbol}")
    block = match.group(1)
    types = re.search(r"\.types\s*=\s*\{TYPE_([A-Z]+),\s*TYPE_([A-Z]+)\}", block)
    if not types:
        raise ValueError(f"Missing types {symbol}")
    name = display_names.get(symbol, symbol.replace("_", " "))
    abilities = re.search(r"\.abilities\s*=\s*\{ABILITY_([A-Z0-9_]+),\s*ABILITY_([A-Z0-9_]+)\}", block)
    if not abilities: raise ValueError(f"Missing abilities {symbol}")
    ability_ids = {s: int(n) for s, n in re.findall(r"#define ABILITY_([A-Z0-9_]+)\s+(\d+)", ability_constants)}
    rows.append(
        f'    {{{number}, "{name}", PokemonType::{type_map[types.group(1)]}, '
        f'PokemonType::{type_map[types.group(2)]}, {field(block,"baseHP")}, '
        f'{field(block,"baseAttack")}, {field(block,"baseDefense")}, {field(block,"baseSpAttack")}, {field(block,"baseSpDefense")}, {field(block,"baseSpeed")}, '
        f'{field(block,"catchRate")}, {field(block,"expYield")}, GrowthRate::{growth_map[field(block,"growthRate").removeprefix("GROWTH_")]}, {ability_ids[abilities.group(1)]}, {ability_ids[abilities.group(2)]}}},'
    )

# Keep original level evolutions. Convert stones/trades/friendship to deterministic
# levels inside Generation I. Branches outside 1..151 are ignored.
evolutions = []
for source_symbol, entries in re.findall(r"\[SPECIES_([A-Z0-9_]+)\]\s*=\s*\{(.*?)\},?\n", evolution_source, re.S):
    source_id = symbol_to_id.get(source_symbol)
    if not source_id:
        continue
    candidates = re.findall(r"\{(EVO_[A-Z_]+),\s*([^,]+),\s*SPECIES_([A-Z0-9_]+)\}", entries)
    for method, parameter, target_symbol in candidates:
        target_id = symbol_to_id.get(target_symbol)
        if not target_id:
            continue
        if method == "EVO_LEVEL":
            level = int(parameter)
        elif method.startswith("EVO_ITEM"):
            level = 36
        elif method.startswith("EVO_TRADE"):
            level = 40
        elif method.startswith("EVO_FRIENDSHIP"):
            level = 30
        else:
            level = 36
        evolutions.append((source_id, target_id, level))
        break  # Kanto branches choose the first canonical target.

content = "// Generated by scripts/generate_pokemon_data.py from local pokefirered data.\n"
content += "constexpr SpeciesData kSpecies[] = {\n" + "\n".join(rows) + "\n};\n\n"
content += "constexpr EvolutionData kEvolutions[] = {\n"
content += "\n".join(f"    {{{a}, {b}, {level}}}," for a, b, level in evolutions)
content += "\n};\n"
content += "\nconstexpr AbilityData kAbilities[] = {\n"
for symbol, number in sorted(ability_ids.items(), key=lambda item: item[1]):
    content += f'    {{{number}, "{symbol.replace("_", " ")}"}},\n'
content += "};\n"

wild_data = json.loads((DECOMP / "src/data/wild_encounters.json").read_text(encoding="utf-8"))
wild_levels: dict[int, int] = {}
wild_counts: dict[int, int] = {}
for group in wild_data["wild_encounter_groups"]:
    for encounter in group["encounters"]:
        for field_name, field_value in encounter.items():
            if not field_name.endswith("_mons") or not isinstance(field_value, dict):
                continue
            for mon in field_value.get("mons", []):
                symbol = mon["species"].removeprefix("SPECIES_")
                species_id = symbol_to_id.get(symbol)
                if not species_id:
                    continue
                wild_levels[species_id] = min(wild_levels.get(species_id, 100), int(mon["min_level"]))
                wild_counts[species_id] = wild_counts.get(species_id, 0) + 1

evolution_unlock = {target: level for _, target, level in evolutions}
legendary = set(range(144, 152))
content += "\nconstexpr EncounterSpecies kEncounterSpecies[] = {\n"
for species_id, _ in species:
    unlock = wild_levels.get(species_id, evolution_unlock.get(species_id, 25))
    weight = max(2, min(20, wild_counts.get(species_id, 2)))
    if species_id in legendary:
        unlock, weight = (70 if species_id == 150 else 50), 1
    elif species_id in (1, 4, 7):
        unlock, weight = 5, 2
    content += f"    {{{species_id}, {unlock}, {weight}}},\n"
content += "};\n"
OUT.write_text(content, encoding="utf-8", newline="\n")
print(f"Generated {len(rows)} species and {len(evolutions)} Kanto evolutions")
